### ISSUE TITLE
Always set `from` and `to` options

### ISSUE THREAD

**Issue by ai** [dbisso/grunt-split-styles#1]
Now you set `from` and `to` option only if source map is enabled. It is bad, because:
- PostCSS parser uses `from` option to show syntax error messages.
- PostCSS will try to autodetect previous map file with `from` options.

**Comment by dbisso** [comment]
Thanks for taking the time to look at the plugin. I have updated it to rely on PostCSS's automatic source map detection now.

See: d58562fd99448edf65fa5891c1af2fecf7b0bd7f

**Comment by ai** [comment]
Nice :)
