### ISSUE TITLE
'pattern' and 'mediaPattern' returned as empty objects

### ISSUE THREAD

**Issue by spacedawwwg** [dbisso/grunt-split-styles#2]
My config:

``` js
split_styles: {
    rtl: {
        options: {
            pattern: /\.rtl/,
            output: '_styles/main.rtl.css'
        },
        files: {
            '_styles/main.css' : '_styles/main.css'
        }
    }
}
```

grunt --verbose outputs:

```
Files: _styles/main.css -> _styles/main.css
Options: separator="", pattern={}, remove, mediaPattern=false, unwrapMedia=false, output="_styles/main.rtl.css"
```

Looks like the pattern is not recognised.

**Comment by dbisso** [comment]
Thanks for the report. Does the actual splitting process still work for you?

I think that Grunt's logging function doesn't output RegExp objects: it just prints them as empty objects (`{}`) rather than showing the pattern you are matching against. The default value for `mediaPattern` is false so that is correct in this instance.

**Comment by spacedawwwg** [comment]
It does. My mistake, for some reason it wasn't working before. Looks like I have fixed an issue that wasn't really an issue.

**Comment by dbisso** [comment]
No problem - it didn't make sense to me until I went digging into the Grunt code. 

I'll have a look at your PR though as it might be good to have flexibility to specify the pattern as a string or a RegExp.

**Comment by spacedawwwg** [comment]
Before i start looking, is there a way to test if a rule/selector is nested in a media query - if so, include the media query?

**Comment by dbisso** [comment]
Not at the moment, but I think it should be possible. Did you have a use case in mind?

**Comment by dbisso** [comment]
@spacedawwwg In `v0.2.0` you should now be able include the parent media query if a selector matches by using the following for options.pattern:

``` js
pattern: {
  match: /\.some-class/,
  matchParent: true
}
```
